name: main
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Generate GitHub Pages
      run: |
        set -x
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # Delete the `docs` directory as it will be fully generated
        rm -rf docs
        
        # Build the CRA application for GitHub Pages
        npm install
        npm run build
        mv build docs
        
        # Add generated GitHub Pages to Git stage
        git add docs
        
        # Capture the current screenshot
        npm run screenshot
        git add screenshot.png
        
        # Reset unstaged changes to prevent `git commit` from yelling if there's changes outside of `docs`
        git checkout -- .
        
        # Commit the changes to the Git repository to deploy GitHub Pages (if any)
        if git diff-index --quiet HEAD --; then
          exit
        fi
        git commit -m "Generate GitHub Pages"

        # Pull before pushing to integrate fast forward changes if any
        git pull --rebase
        
        # Push the changes to GitHub where it will cause another workflow which will kill itself immediately due to ***NO_CI***
        git push
